// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostAccountOKCode is the HTTP code returned for type PostAccountOK
const PostAccountOKCode int = 200

/*
PostAccountOK Success

swagger:response postAccountOK
*/
type PostAccountOK struct {

	/*
	  In: Body
	*/
	Payload *PostAccountOKBody `json:"body,omitempty"`
}

// NewPostAccountOK creates PostAccountOK with default headers values
func NewPostAccountOK() *PostAccountOK {

	return &PostAccountOK{}
}

// WithPayload adds the payload to the post account o k response
func (o *PostAccountOK) WithPayload(payload *PostAccountOKBody) *PostAccountOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post account o k response
func (o *PostAccountOK) SetPayload(payload *PostAccountOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAccountOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAccountBadRequestCode is the HTTP code returned for type PostAccountBadRequest
const PostAccountBadRequestCode int = 400

/*
PostAccountBadRequest Bad Request

swagger:response postAccountBadRequest
*/
type PostAccountBadRequest struct {

	/*
	  In: Body
	*/
	Payload *PostAccountBadRequestBody `json:"body,omitempty"`
}

// NewPostAccountBadRequest creates PostAccountBadRequest with default headers values
func NewPostAccountBadRequest() *PostAccountBadRequest {

	return &PostAccountBadRequest{}
}

// WithPayload adds the payload to the post account bad request response
func (o *PostAccountBadRequest) WithPayload(payload *PostAccountBadRequestBody) *PostAccountBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post account bad request response
func (o *PostAccountBadRequest) SetPayload(payload *PostAccountBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAccountBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAccountUnauthorizedCode is the HTTP code returned for type PostAccountUnauthorized
const PostAccountUnauthorizedCode int = 401

/*
PostAccountUnauthorized Unauthorized

swagger:response postAccountUnauthorized
*/
type PostAccountUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *PostAccountUnauthorizedBody `json:"body,omitempty"`
}

// NewPostAccountUnauthorized creates PostAccountUnauthorized with default headers values
func NewPostAccountUnauthorized() *PostAccountUnauthorized {

	return &PostAccountUnauthorized{}
}

// WithPayload adds the payload to the post account unauthorized response
func (o *PostAccountUnauthorized) WithPayload(payload *PostAccountUnauthorizedBody) *PostAccountUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post account unauthorized response
func (o *PostAccountUnauthorized) SetPayload(payload *PostAccountUnauthorizedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAccountUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAccountInternalServerErrorCode is the HTTP code returned for type PostAccountInternalServerError
const PostAccountInternalServerErrorCode int = 500

/*
PostAccountInternalServerError Internal Server Error

swagger:response postAccountInternalServerError
*/
type PostAccountInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *PostAccountInternalServerErrorBody `json:"body,omitempty"`
}

// NewPostAccountInternalServerError creates PostAccountInternalServerError with default headers values
func NewPostAccountInternalServerError() *PostAccountInternalServerError {

	return &PostAccountInternalServerError{}
}

// WithPayload adds the payload to the post account internal server error response
func (o *PostAccountInternalServerError) WithPayload(payload *PostAccountInternalServerErrorBody) *PostAccountInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post account internal server error response
func (o *PostAccountInternalServerError) SetPayload(payload *PostAccountInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAccountInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
