// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AccountUpdated account updated
//
// swagger:model AccountUpdated
type AccountUpdated struct {

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this account updated
func (m *AccountUpdated) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this account updated based on context it is used
func (m *AccountUpdated) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AccountUpdated) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccountUpdated) UnmarshalBinary(b []byte) error {
	var res AccountUpdated
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
