// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LinkUpdate link update
//
// swagger:model LinkUpdate
type LinkUpdate struct {

	// new long url
	NewLongURL string `json:"new_long_url,omitempty"`

	// short url key
	ShortURLKey string `json:"short_url_key,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// tracking status
	TrackingStatus string `json:"tracking_status,omitempty"`
}

// Validate validates this link update
func (m *LinkUpdate) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this link update based on context it is used
func (m *LinkUpdate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LinkUpdate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LinkUpdate) UnmarshalBinary(b []byte) error {
	var res LinkUpdate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
