// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// URLCreated URL created
//
// swagger:model URLCreated
type URLCreated struct {

	// short url
	ShortURL string `json:"short_url,omitempty"`

	// short url key
	ShortURLKey string `json:"short_url_key,omitempty"`
}

// Validate validates this URL created
func (m *URLCreated) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this URL created based on context it is used
func (m *URLCreated) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *URLCreated) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *URLCreated) UnmarshalBinary(b []byte) error {
	var res URLCreated
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
