// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/elbombardi/squrl/src/api_service/api/models"
)

// CreateAccountOKCode is the HTTP code returned for type CreateAccountOK
const CreateAccountOKCode int = 200

/*
CreateAccountOK Success

swagger:response createAccountOK
*/
type CreateAccountOK struct {

	/*
	  In: Body
	*/
	Payload *models.AccountCreated `json:"body,omitempty"`
}

// NewCreateAccountOK creates CreateAccountOK with default headers values
func NewCreateAccountOK() *CreateAccountOK {

	return &CreateAccountOK{}
}

// WithPayload adds the payload to the create account o k response
func (o *CreateAccountOK) WithPayload(payload *models.AccountCreated) *CreateAccountOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create account o k response
func (o *CreateAccountOK) SetPayload(payload *models.AccountCreated) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAccountOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateAccountBadRequestCode is the HTTP code returned for type CreateAccountBadRequest
const CreateAccountBadRequestCode int = 400

/*
CreateAccountBadRequest Bad Request

swagger:response createAccountBadRequest
*/
type CreateAccountBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateAccountBadRequest creates CreateAccountBadRequest with default headers values
func NewCreateAccountBadRequest() *CreateAccountBadRequest {

	return &CreateAccountBadRequest{}
}

// WithPayload adds the payload to the create account bad request response
func (o *CreateAccountBadRequest) WithPayload(payload *models.Error) *CreateAccountBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create account bad request response
func (o *CreateAccountBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAccountBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateAccountUnauthorizedCode is the HTTP code returned for type CreateAccountUnauthorized
const CreateAccountUnauthorizedCode int = 401

/*
CreateAccountUnauthorized Unauthorized

swagger:response createAccountUnauthorized
*/
type CreateAccountUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateAccountUnauthorized creates CreateAccountUnauthorized with default headers values
func NewCreateAccountUnauthorized() *CreateAccountUnauthorized {

	return &CreateAccountUnauthorized{}
}

// WithPayload adds the payload to the create account unauthorized response
func (o *CreateAccountUnauthorized) WithPayload(payload *models.Error) *CreateAccountUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create account unauthorized response
func (o *CreateAccountUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAccountUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateAccountInternalServerErrorCode is the HTTP code returned for type CreateAccountInternalServerError
const CreateAccountInternalServerErrorCode int = 500

/*
CreateAccountInternalServerError Internal Server Error

swagger:response createAccountInternalServerError
*/
type CreateAccountInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateAccountInternalServerError creates CreateAccountInternalServerError with default headers values
func NewCreateAccountInternalServerError() *CreateAccountInternalServerError {

	return &CreateAccountInternalServerError{}
}

// WithPayload adds the payload to the create account internal server error response
func (o *CreateAccountInternalServerError) WithPayload(payload *models.Error) *CreateAccountInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create account internal server error response
func (o *CreateAccountInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAccountInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
