version: "3.3"

services:
  db:
    image: postgres
    container_name: platform_db
    logging:
        driver: none
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  db_init:
    build:
      context: .
      dockerfile: db/Dockerfile      
    entrypoint: [ '/bin/sh', '-c' ]
    environment:
      DB_DRIVER: postgres
      DB_SOURCE: postgresql://postgres:postgres@db:5432/postgres?sslmode=disable
    command: |
      "
      # Wait for Postgres server : 
      sh /app/wait-for.sh db:5432 -- /app/migrate --path /app/migration/ --database postgresql://postgres:postgres@db:5432/postgres?sslmode=disable up
      "


  api_service:
    container_name: squrl_api_server
    build:
      context: .
      dockerfile: orders_service/Dockerfile
    environment:
      KAFKA_ADDRESS: broker:29092
      ORDERS_SUBMIT_TOPIC_TEMPLATE: orders-submit-{transactionType}-topic
      ORDERS_CANCELLATION_TOPIC: orders-cancellation-topic
      DB_DRIVER: postgres
      DB_SOURCE: postgresql://postgres:postgres@db:5432/postgres?sslmode=disable
      DB_MAX_IDLE_CONNS: 5
      DB_MAX_OPEN_CONNS: 10
      DB_CONN_MAX_IDLE_TIME: 1
      DB_CONN_MAX_LIFE_TIME: 30
      VALIDATION_SERVICE_URL: http://validation_service:8081
      HOST: 0.0.0.0
      ENVIRONMENT: dev
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - db_init
      - db
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # Launching Orders server :
      # echo -e 'Waiting for mock validation service to start...'
      # sh /app/wait-for.sh validator:8081 -- echo Validator reached! 
      echo -e 'Waiting for Postgres to start...'
      sh /app/wait-for.sh db:5432 -- /app/orders-server --port 8080 
      "

  validation_service:
    container_name: platform_validation_server
    build:
      context: .
      dockerfile: validation_service/Dockerfile
    environment:
      USER_PROFILE_SERVICE_URL: http://users_service:8083
      BANK_PROFILE_SERVICE_URL: http://mock_bank_profile_service:8090
      BANK_ACCOUNT_SERVICE_URL: http://mock_bank_account_service:8091
      HOST: 0.0.0.0
      ENVIRONMENT: dev
    expose:
      - "8081"
    ports:
      - "8081:8081"
    depends_on:
      - db_init
      - db
    entrypoint: ["/app/validation-server", "--port", "8081"]