// Code generated by go-swagger; DO NOT EDIT.

package urls

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/elbombardi/squrl/src/api_service/api/models"
)

// CreateURLOKCode is the HTTP code returned for type CreateURLOK
const CreateURLOKCode int = 200

/*
CreateURLOK Success

swagger:response createUrlOK
*/
type CreateURLOK struct {

	/*
	  In: Body
	*/
	Payload *models.URLCreated `json:"body,omitempty"`
}

// NewCreateURLOK creates CreateURLOK with default headers values
func NewCreateURLOK() *CreateURLOK {

	return &CreateURLOK{}
}

// WithPayload adds the payload to the create Url o k response
func (o *CreateURLOK) WithPayload(payload *models.URLCreated) *CreateURLOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create Url o k response
func (o *CreateURLOK) SetPayload(payload *models.URLCreated) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateURLOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateURLBadRequestCode is the HTTP code returned for type CreateURLBadRequest
const CreateURLBadRequestCode int = 400

/*
CreateURLBadRequest Bad Request

swagger:response createUrlBadRequest
*/
type CreateURLBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateURLBadRequest creates CreateURLBadRequest with default headers values
func NewCreateURLBadRequest() *CreateURLBadRequest {

	return &CreateURLBadRequest{}
}

// WithPayload adds the payload to the create Url bad request response
func (o *CreateURLBadRequest) WithPayload(payload *models.Error) *CreateURLBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create Url bad request response
func (o *CreateURLBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateURLBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateURLUnauthorizedCode is the HTTP code returned for type CreateURLUnauthorized
const CreateURLUnauthorizedCode int = 401

/*
CreateURLUnauthorized Unauthorized

swagger:response createUrlUnauthorized
*/
type CreateURLUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateURLUnauthorized creates CreateURLUnauthorized with default headers values
func NewCreateURLUnauthorized() *CreateURLUnauthorized {

	return &CreateURLUnauthorized{}
}

// WithPayload adds the payload to the create Url unauthorized response
func (o *CreateURLUnauthorized) WithPayload(payload *models.Error) *CreateURLUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create Url unauthorized response
func (o *CreateURLUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateURLUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateURLInternalServerErrorCode is the HTTP code returned for type CreateURLInternalServerError
const CreateURLInternalServerErrorCode int = 500

/*
CreateURLInternalServerError Internal Server Error

swagger:response createUrlInternalServerError
*/
type CreateURLInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateURLInternalServerError creates CreateURLInternalServerError with default headers values
func NewCreateURLInternalServerError() *CreateURLInternalServerError {

	return &CreateURLInternalServerError{}
}

// WithPayload adds the payload to the create Url internal server error response
func (o *CreateURLInternalServerError) WithPayload(payload *models.Error) *CreateURLInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create Url internal server error response
func (o *CreateURLInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateURLInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
