// Code generated by go-swagger; DO NOT EDIT.

package urls

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateURLHandlerFunc turns a function with the right signature into a create URL handler
type CreateURLHandlerFunc func(CreateURLParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateURLHandlerFunc) Handle(params CreateURLParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreateURLHandler interface for that can handle valid create URL params
type CreateURLHandler interface {
	Handle(CreateURLParams, interface{}) middleware.Responder
}

// NewCreateURL creates a new http.Handler for the create URL operation
func NewCreateURL(ctx *middleware.Context, handler CreateURLHandler) *CreateURL {
	return &CreateURL{Context: ctx, Handler: handler}
}

/*
	CreateURL swagger:route POST /urls urls createUrl

# Create a new URL

Create a new URL
*/
type CreateURL struct {
	Context *middleware.Context
	Handler CreateURLHandler
}

func (o *CreateURL) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateURLParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
