// Code generated by go-swagger; DO NOT EDIT.

package urls

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/elbombardi/squrl/src/api_service/api/models"
)

// UpdateURLOKCode is the HTTP code returned for type UpdateURLOK
const UpdateURLOKCode int = 200

/*
UpdateURLOK Success

swagger:response updateUrlOK
*/
type UpdateURLOK struct {

	/*
	  In: Body
	*/
	Payload *UpdateURLOKBody `json:"body,omitempty"`
}

// NewUpdateURLOK creates UpdateURLOK with default headers values
func NewUpdateURLOK() *UpdateURLOK {

	return &UpdateURLOK{}
}

// WithPayload adds the payload to the update Url o k response
func (o *UpdateURLOK) WithPayload(payload *UpdateURLOKBody) *UpdateURLOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update Url o k response
func (o *UpdateURLOK) SetPayload(payload *UpdateURLOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateURLOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateURLBadRequestCode is the HTTP code returned for type UpdateURLBadRequest
const UpdateURLBadRequestCode int = 400

/*
UpdateURLBadRequest Bad Request

swagger:response updateUrlBadRequest
*/
type UpdateURLBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateURLBadRequest creates UpdateURLBadRequest with default headers values
func NewUpdateURLBadRequest() *UpdateURLBadRequest {

	return &UpdateURLBadRequest{}
}

// WithPayload adds the payload to the update Url bad request response
func (o *UpdateURLBadRequest) WithPayload(payload *models.Error) *UpdateURLBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update Url bad request response
func (o *UpdateURLBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateURLBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateURLUnauthorizedCode is the HTTP code returned for type UpdateURLUnauthorized
const UpdateURLUnauthorizedCode int = 401

/*
UpdateURLUnauthorized Unauthorized

swagger:response updateUrlUnauthorized
*/
type UpdateURLUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateURLUnauthorized creates UpdateURLUnauthorized with default headers values
func NewUpdateURLUnauthorized() *UpdateURLUnauthorized {

	return &UpdateURLUnauthorized{}
}

// WithPayload adds the payload to the update Url unauthorized response
func (o *UpdateURLUnauthorized) WithPayload(payload *models.Error) *UpdateURLUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update Url unauthorized response
func (o *UpdateURLUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateURLUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateURLNotFoundCode is the HTTP code returned for type UpdateURLNotFound
const UpdateURLNotFoundCode int = 404

/*
UpdateURLNotFound Not Found

swagger:response updateUrlNotFound
*/
type UpdateURLNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateURLNotFound creates UpdateURLNotFound with default headers values
func NewUpdateURLNotFound() *UpdateURLNotFound {

	return &UpdateURLNotFound{}
}

// WithPayload adds the payload to the update Url not found response
func (o *UpdateURLNotFound) WithPayload(payload *models.Error) *UpdateURLNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update Url not found response
func (o *UpdateURLNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateURLNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateURLInternalServerErrorCode is the HTTP code returned for type UpdateURLInternalServerError
const UpdateURLInternalServerErrorCode int = 500

/*
UpdateURLInternalServerError Internal Server Error

swagger:response updateUrlInternalServerError
*/
type UpdateURLInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateURLInternalServerError creates UpdateURLInternalServerError with default headers values
func NewUpdateURLInternalServerError() *UpdateURLInternalServerError {

	return &UpdateURLInternalServerError{}
}

// WithPayload adds the payload to the update Url internal server error response
func (o *UpdateURLInternalServerError) WithPayload(payload *models.Error) *UpdateURLInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update Url internal server error response
func (o *UpdateURLInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateURLInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
