// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: clicks.sql

package db

import (
	"context"
	"database/sql"
)

const insertNewClick = `-- name: InsertNewClick :exec
INSERT INTO clicks (short_url_id, user_agent, ip_address)
VALUES ($1, $2, $3)
`

type InsertNewClickParams struct {
	ShortUrlID int32
	UserAgent  sql.NullString
	IpAddress  sql.NullString
}

func (q *Queries) InsertNewClick(ctx context.Context, arg InsertNewClickParams) error {
	_, err := q.db.ExecContext(ctx, insertNewClick, arg.ShortUrlID, arg.UserAgent, arg.IpAddress)
	return err
}
