// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: link.sql

package db

import (
	"context"
	"database/sql"
)

const insertNewClick = `-- name: InsertNewClick :exec
INSERT INTO click (id, short_url_id, click_date_time, user_agent, ip_address)
VALUES ($1, $2, $3, $4, $5)
`

type InsertNewClickParams struct {
	ID            int32
	ShortUrlID    int32
	ClickDateTime sql.NullTime
	UserAgent     sql.NullString
	IpAddress     sql.NullString
}

func (q *Queries) InsertNewClick(ctx context.Context, arg InsertNewClickParams) error {
	_, err := q.db.ExecContext(ctx, insertNewClick,
		arg.ID,
		arg.ShortUrlID,
		arg.ClickDateTime,
		arg.UserAgent,
		arg.IpAddress,
	)
	return err
}
