// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
)

// Table holding click information
type Click struct {
	ID         int32
	ShortUrlID int32
	// Timestamp of click
	ClickDateTime sql.NullTime
	UserAgent     sql.NullString
	IpAddress     sql.NullString
}

// Table holding Customer information
type Customer struct {
	ID int32
	// 3 characters, case-sensitive
	Prefix   string
	Username string
	Email    string
	// API key
	ApiKey string
	// e: enabled, d: disabled
	Status string
	// Timestamp of creation
	CreatedAt sql.NullTime
	// Timestamp of last update
	UpdatedAt sql.NullTime
}

// Table holding short URL information
type ShortUrl struct {
	ID int32
	// 6 characters, case-sensitive
	ShortUrlKey sql.NullString
	CustomerID  int32
	LongUrl     string
	// e: enabled, d: disabled
	Status sql.NullString
	// Aggregate updated by the redirection server
	ClickCount sql.NullInt32
	// Aggregate set by the redirection server
	FirstClickDateTime sql.NullTime
	// Aggregate set by the redirection server
	LastClickDateTime sql.NullTime
	// Timestamp of creation
	CreatedAt sql.NullTime
	// Timestamp of last update
	UpdatedAt sql.NullTime
}
