CREATE TABLE "account" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "prefix" varchar(3) UNIQUE NOT NULL,
  "username" varchar UNIQUE NOT NULL,
  "email" varchar NOT NULL,
  "hashed_password" varchar UNIQUE NOT NULL,
  "enabled" bool NOT NULL DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "url" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "short_url_key" varchar,
  "account_id" int NOT NULL,
  "long_url" varchar NOT NULL,
  "enabled" boolean NOT NULL DEFAULT true,
  "tracking_enabled" boolean NOT NULL DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "click" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "url_id" int NOT NULL,
  "click_date_time" timestamp DEFAULT (now()),
  "user_agent" varchar,
  "ip_address" varchar
);

CREATE INDEX ON "account" ("prefix");

CREATE INDEX ON "account" ("username");

CREATE INDEX ON "url" ("account_id");

CREATE UNIQUE INDEX ON "url" ("short_url_key", "account_id");

CREATE INDEX ON "click" ("url_id");

COMMENT ON TABLE "account" IS 'Table holding Account information';

COMMENT ON COLUMN "account"."prefix" IS '3 characters, case-sensitive';

COMMENT ON COLUMN "account"."hashed_password" IS 'Hashed password';

COMMENT ON COLUMN "account"."enabled" IS 'A flag that enables/disables the account and its urls';

COMMENT ON COLUMN "account"."created_at" IS 'Timestamp of creation';

COMMENT ON COLUMN "account"."updated_at" IS 'Timestamp of last update';

COMMENT ON TABLE "url" IS 'Table holding URL information';

COMMENT ON COLUMN "url"."short_url_key" IS '6 characters, case-sensitive';

COMMENT ON COLUMN "url"."enabled" IS 'A flag to enable/disable the url redirection';

COMMENT ON COLUMN "url"."tracking_enabled" IS 'A flag that enable/disable url tracking on redirection';

COMMENT ON COLUMN "url"."created_at" IS 'Timestamp of creation';

COMMENT ON COLUMN "url"."updated_at" IS 'Timestamp of last update';

COMMENT ON TABLE "click" IS 'Table holding click information';

COMMENT ON COLUMN "click"."click_date_time" IS 'Timestamp of click';

ALTER TABLE "url" ADD FOREIGN KEY ("account_id") REFERENCES "account" ("id");

ALTER TABLE "click" ADD FOREIGN KEY ("url_id") REFERENCES "url" ("id");
