// Code generated by go-swagger; DO NOT EDIT.

// Package api SQURL - ADMIN API
//
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /v2
//	Version: 2.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package api
