// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "SQURL - ADMIN API",
    "version": "1.0.0"
  },
  "basePath": "/v1",
  "paths": {
    "/accounts": {
      "put": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "description": "Update an account",
        "tags": [
          "accounts"
        ],
        "summary": "Update an account",
        "operationId": "UpdateAccount",
        "parameters": [
          {
            "type": "string",
            "description": "Bearer \u003cJWT Token\u003e",
            "name": "Authorization",
            "in": "header"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/AccountUpdate"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/AccountUpdated"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "description": "Create a new account",
        "tags": [
          "accounts"
        ],
        "summary": "Create an account",
        "operationId": "CreateAccount",
        "parameters": [
          {
            "type": "string",
            "description": "Bearer \u003cJWT Token\u003e",
            "name": "Authorization",
            "in": "header"
          },
          {
            "name": "account",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Account"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/AccountCreated"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/health": {
      "get": {
        "description": "Health check endpoint",
        "tags": [
          "general"
        ],
        "summary": "Healthcheck",
        "operationId": "Healthcheck",
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/links": {
      "put": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "description": "Update Link",
        "tags": [
          "links"
        ],
        "summary": "Update a link",
        "operationId": "UpdateLink",
        "parameters": [
          {
            "type": "string",
            "description": "Bearer \u003cJWT Token\u003e",
            "name": "Authorization",
            "in": "header"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/LinkUpdate"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/LinkUpdated"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "description": "Create a new link",
        "tags": [
          "links"
        ],
        "summary": "Create a new linkL",
        "operationId": "CreateLink",
        "parameters": [
          {
            "type": "string",
            "description": "Bearer \u003cJWT Token\u003e",
            "name": "Authorization",
            "in": "header"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Link"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/LinkCreated"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/login": {
      "post": {
        "description": "Returns JWT token for authorized user",
        "consumes": [
          "application/json"
        ],
        "tags": [
          "general"
        ],
        "summary": "Login",
        "operationId": "Login",
        "parameters": [
          {
            "description": "Login Payload",
            "name": "login",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/LoginInfo"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful login",
            "schema": {
              "$ref": "#/definitions/LoginSuccess"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Account": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "AccountCreated": {
      "type": "object",
      "properties": {
        "password": {
          "type": "string"
        },
        "prefix": {
          "type": "string"
        }
      }
    },
    "AccountUpdate": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "AccountUpdated": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Link": {
      "type": "object",
      "properties": {
        "long_url": {
          "type": "string"
        }
      }
    },
    "LinkCreated": {
      "type": "object",
      "properties": {
        "short_url": {
          "type": "string"
        },
        "short_url_key": {
          "type": "string"
        }
      }
    },
    "LinkUpdate": {
      "type": "object",
      "properties": {
        "new_long_url": {
          "type": "string"
        },
        "short_url_key": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "tracking_status": {
          "type": "string"
        }
      }
    },
    "LinkUpdated": {
      "type": "object",
      "properties": {
        "long_url": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "tracking_status": {
          "type": "string"
        }
      }
    },
    "LoginInfo": {
      "type": "object",
      "properties": {
        "password": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "LoginSuccess": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "token": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "SQURL - ADMIN API",
    "version": "1.0.0"
  },
  "basePath": "/v1",
  "paths": {
    "/accounts": {
      "put": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "description": "Update an account",
        "tags": [
          "accounts"
        ],
        "summary": "Update an account",
        "operationId": "UpdateAccount",
        "parameters": [
          {
            "type": "string",
            "description": "Bearer \u003cJWT Token\u003e",
            "name": "Authorization",
            "in": "header"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/AccountUpdate"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/AccountUpdated"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "description": "Create a new account",
        "tags": [
          "accounts"
        ],
        "summary": "Create an account",
        "operationId": "CreateAccount",
        "parameters": [
          {
            "type": "string",
            "description": "Bearer \u003cJWT Token\u003e",
            "name": "Authorization",
            "in": "header"
          },
          {
            "name": "account",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Account"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/AccountCreated"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/health": {
      "get": {
        "description": "Health check endpoint",
        "tags": [
          "general"
        ],
        "summary": "Healthcheck",
        "operationId": "Healthcheck",
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/links": {
      "put": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "description": "Update Link",
        "tags": [
          "links"
        ],
        "summary": "Update a link",
        "operationId": "UpdateLink",
        "parameters": [
          {
            "type": "string",
            "description": "Bearer \u003cJWT Token\u003e",
            "name": "Authorization",
            "in": "header"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/LinkUpdate"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/LinkUpdated"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "description": "Create a new link",
        "tags": [
          "links"
        ],
        "summary": "Create a new linkL",
        "operationId": "CreateLink",
        "parameters": [
          {
            "type": "string",
            "description": "Bearer \u003cJWT Token\u003e",
            "name": "Authorization",
            "in": "header"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Link"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/LinkCreated"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/login": {
      "post": {
        "description": "Returns JWT token for authorized user",
        "consumes": [
          "application/json"
        ],
        "tags": [
          "general"
        ],
        "summary": "Login",
        "operationId": "Login",
        "parameters": [
          {
            "description": "Login Payload",
            "name": "login",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/LoginInfo"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful login",
            "schema": {
              "$ref": "#/definitions/LoginSuccess"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Account": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "AccountCreated": {
      "type": "object",
      "properties": {
        "password": {
          "type": "string"
        },
        "prefix": {
          "type": "string"
        }
      }
    },
    "AccountUpdate": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "AccountUpdated": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Link": {
      "type": "object",
      "properties": {
        "long_url": {
          "type": "string"
        }
      }
    },
    "LinkCreated": {
      "type": "object",
      "properties": {
        "short_url": {
          "type": "string"
        },
        "short_url_key": {
          "type": "string"
        }
      }
    },
    "LinkUpdate": {
      "type": "object",
      "properties": {
        "new_long_url": {
          "type": "string"
        },
        "short_url_key": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "tracking_status": {
          "type": "string"
        }
      }
    },
    "LinkUpdated": {
      "type": "object",
      "properties": {
        "long_url": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "tracking_status": {
          "type": "string"
        }
      }
    },
    "LoginInfo": {
      "type": "object",
      "properties": {
        "password": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "LoginSuccess": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "token": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
}
