name: redirection_service_docker_ci

on:
  push:
    branches: [ "main" ]
    paths:
      - src/api_service/**
      - src/db/**

  pull_request:
    branches: [ "main" ]
    paths:
      - src/redirection_service/**
      - src/db/**
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file src/redirection_service/Dockerfile --tag squrl_redirection_service:$(date +%s)
