// Code generated by go-swagger; DO NOT EDIT.

package links

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/elbombardi/squrl/src/api_service/api/models"
)

// CreateLinkOKCode is the HTTP code returned for type CreateLinkOK
const CreateLinkOKCode int = 200

/*
CreateLinkOK Success

swagger:response createLinkOK
*/
type CreateLinkOK struct {

	/*
	  In: Body
	*/
	Payload *models.LinkCreated `json:"body,omitempty"`
}

// NewCreateLinkOK creates CreateLinkOK with default headers values
func NewCreateLinkOK() *CreateLinkOK {

	return &CreateLinkOK{}
}

// WithPayload adds the payload to the create link o k response
func (o *CreateLinkOK) WithPayload(payload *models.LinkCreated) *CreateLinkOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create link o k response
func (o *CreateLinkOK) SetPayload(payload *models.LinkCreated) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateLinkOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateLinkBadRequestCode is the HTTP code returned for type CreateLinkBadRequest
const CreateLinkBadRequestCode int = 400

/*
CreateLinkBadRequest Bad Request

swagger:response createLinkBadRequest
*/
type CreateLinkBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateLinkBadRequest creates CreateLinkBadRequest with default headers values
func NewCreateLinkBadRequest() *CreateLinkBadRequest {

	return &CreateLinkBadRequest{}
}

// WithPayload adds the payload to the create link bad request response
func (o *CreateLinkBadRequest) WithPayload(payload *models.Error) *CreateLinkBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create link bad request response
func (o *CreateLinkBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateLinkBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateLinkUnauthorizedCode is the HTTP code returned for type CreateLinkUnauthorized
const CreateLinkUnauthorizedCode int = 401

/*
CreateLinkUnauthorized Unauthorized

swagger:response createLinkUnauthorized
*/
type CreateLinkUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateLinkUnauthorized creates CreateLinkUnauthorized with default headers values
func NewCreateLinkUnauthorized() *CreateLinkUnauthorized {

	return &CreateLinkUnauthorized{}
}

// WithPayload adds the payload to the create link unauthorized response
func (o *CreateLinkUnauthorized) WithPayload(payload *models.Error) *CreateLinkUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create link unauthorized response
func (o *CreateLinkUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateLinkUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateLinkInternalServerErrorCode is the HTTP code returned for type CreateLinkInternalServerError
const CreateLinkInternalServerErrorCode int = 500

/*
CreateLinkInternalServerError Internal Server Error

swagger:response createLinkInternalServerError
*/
type CreateLinkInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateLinkInternalServerError creates CreateLinkInternalServerError with default headers values
func NewCreateLinkInternalServerError() *CreateLinkInternalServerError {

	return &CreateLinkInternalServerError{}
}

// WithPayload adds the payload to the create link internal server error response
func (o *CreateLinkInternalServerError) WithPayload(payload *models.Error) *CreateLinkInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create link internal server error response
func (o *CreateLinkInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateLinkInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
